<?xml version="1.0" encoding="utf-8"?>
<!-- Quake VR module build settings, imported by ironwail.vcxproj. -->
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>..\..\Quake\vr;..\..\Quake\vr\external;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <LanguageStandard>stdcpp20</LanguageStandard>
    </ClCompile>
  </ItemDefinitionGroup>
  <ItemGroup>
    <ClCompile Include="..\..\Quake\vr\*.cpp">
      <CompileAs>CompileAsCpp</CompileAs>
      <PrecompiledHeader>NotUsing</PrecompiledHeader>
    </ClCompile>
    <ClInclude Include="..\..\Quake\vr\*.h;..\..\Quake\vr\*.hpp" />
  </ItemGroup>
</Project>
