<?xml version="1.0" encoding="utf-8"?>
<!-- Quake VR module build settings, imported by ironwail.vcxproj. -->
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>..\..\Quake\vr;..\..\Quake\vr\external;..\..\Quake\vr\external\box3d\include;..\OpenXR\include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <LanguageStandard>stdcpp20</LanguageStandard>
      <PreprocessorDefinitions Condition="'$(Platform)'=='x64'">QVR_HAVE_OPENXR;%(PreprocessorDefinitions)</PreprocessorDefinitions>
    </ClCompile>
    <Link>
      <!-- Zancle (Quake/vr/external/zancle/README.md): WaitOnAddress. -->
      <AdditionalDependencies>synchronization.lib;%(AdditionalDependencies)</AdditionalDependencies>
    </Link>
    <Link Condition="'$(Platform)'=='x64'">
      <AdditionalDependencies>openxr_loader.lib;%(AdditionalDependencies)</AdditionalDependencies>
      <AdditionalLibraryDirectories>..\OpenXR\lib\x64;%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
    </Link>
    <PostBuildEvent Condition="'$(Platform)'=='x64'">
      <Command>%(Command)
copy "$(SolutionDir)..\OpenXR\lib\x64\openxr_loader.dll" "$(TargetDir)"</Command>
    </PostBuildEvent>
  </ItemDefinitionGroup>
  <ItemGroup>
    <ClCompile Include="..\..\Quake\vr\*.cpp" Exclude="..\..\Quake\vr\vr_jobs.cpp">
      <CompileAs>CompileAsCpp</CompileAs>
      <PrecompiledHeader>NotUsing</PrecompiledHeader>
    </ClCompile>
    <ClInclude Include="..\..\Quake\vr\*.h;..\..\Quake\vr\*.hpp" />
    <!-- Box3D (Quake/vr/external/box3d/README.md): the physics library, C17, single-threaded. -->
    <ClCompile Include="..\..\Quake\vr\external\box3d\src\*.c">
      <CompileAs>CompileAsC</CompileAs>
      <LanguageStandard_C>stdc17</LanguageStandard_C>
      <PrecompiledHeader>NotUsing</PrecompiledHeader>
      <ObjectFileName>$(IntDir)box3d\</ObjectFileName>
      <!-- C4756: "overflow in constant arithmetic", from whole-program optimization folding 1000 * FLT_MAX in the CCD
           stall logging (b3GetStallThreshold, off by default: the comparison with infinity is intended). -->
      <DisableSpecificWarnings>4756;%(DisableSpecificWarnings)</DisableSpecificWarnings>
    </ClCompile>
    <ClInclude Include="..\..\Quake\vr\external\box3d\src\*.h;..\..\Quake\vr\external\box3d\include\box3d\*.h" />
  </ItemGroup>
  <!-- Zancle (Quake/vr/external/zancle/README.md) with vr_jobs.cpp, the game's thread pool: a static library built by
       clang-cl (zancle.vcxproj; vr_jobs.cpp is left out of the glob above). -->
  <ItemGroup>
    <ProjectReference Include="zancle.vcxproj">
      <Project>{E286BCD0-E4E0-4F68-B335-083019EA8E02}</Project>
    </ProjectReference>
  </ItemGroup>
</Project>
