#pragma once

#include "vr_macros.hpp"

// clang-format off
#define EF_BRIGHTFIELD  VRUTIL_POWER_OF_TWO(0)
#define EF_MUZZLEFLASH  VRUTIL_POWER_OF_TWO(1)
#define EF_BRIGHTLIGHT  VRUTIL_POWER_OF_TWO(2)
#define EF_DIMLIGHT     VRUTIL_POWER_OF_TWO(3)
#define EF_VERYDIMLIGHT VRUTIL_POWER_OF_TWO(4)
#define EF_MINIROCKET   VRUTIL_POWER_OF_TWO(5)
#define EF_LAVATRAIL    VRUTIL_POWER_OF_TWO(6)
#define EF_FULLBRIGHT   VRUTIL_POWER_OF_TWO(7)
#define EF_NOSHADOW     VRUTIL_POWER_OF_TWO(8)
#define EF_NOMODELFLAGS VRUTIL_POWER_OF_TWO(9)
// clang-format on
