#pragma once

#define GLM_FORCE_INLINE
#define GLM_CONFIG_SIMD GLM_ENABLE
#define GLM_CONFIG_SWIZZLE GLM_SWIZZLE_OPERATOR
#define GLM_CONFIG_ALIGNED_GENTYPES GLM_ENABLE
#define GLM_CONFIG_ANONYMOUS_STRUCT GLM_ENABLE
#define GLM_FORCE_SWIZZLE
