name: Linux CI
on: [push, pull_request]
jobs:
  build:
    name: Linux / ${{ matrix.compiler }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - compiler: clang
            cxx: clang++
          - compiler: gcc
            cxx: g++
    steps:
    - uses: actions/checkout@v7
    - name: Install Dependencies
      run: sudo apt update && sudo apt install libcurl4-openssl-dev libmpg123-dev libsdl2-dev libvorbis-dev
    - name: Build
      run: make --jobs=3 --keep-going --directory=Quake CC=${{ matrix.compiler }} CXX=${{ matrix.cxx }}
